Repository Volgarenok/spbspu-labs-2024-aads-a, pull requests merged in 2024-05, with the labels that each got.

#35 marishin.leonid/S1
  marishin.leonid/S1/input.cpp
  marishin.leonid/S1/input.hpp
  marishin.leonid/S1/iterator.hpp
  marishin.leonid/S1/linkedList.hpp
  marishin.leonid/S1/main.cpp
  marishin.leonid/S1/node.hpp
Labels: fine, -1

#87 arakelyan.daniil/S2
  arakelyan.daniil/S1/inputData.hpp
  arakelyan.daniil/S2/calculateProc.cpp
  arakelyan.daniil/S2/calculateProc.hpp
  arakelyan.daniil/S2/expressionObject.cpp
  arakelyan.daniil/S2/expressionObject.hpp
  arakelyan.daniil/S2/inputData.cpp
  arakelyan.daniil/S2/inputData.hpp
  arakelyan.daniil/S2/main.cpp
  arakelyan.daniil/S2/queue.hpp
  arakelyan.daniil/S2/stack.hpp
  arakelyan.daniil/S2/transformToPostdix.cpp
  arakelyan.daniil/S2/transformToPostfix.hpp
  arakelyan.daniil/common/list/binList.hpp
Labels: fine, -1

#72 strelyaev.roman/S2
  strelyaev.roman/S1/inputList.cpp
  strelyaev.roman/S1/inputList.hpp
  strelyaev.roman/S1/main.cpp
  strelyaev.roman/S2/calculations.cpp
  strelyaev.roman/S2/calculations.hpp
  strelyaev.roman/S2/conversion.cpp
  strelyaev.roman/S2/conversion.hpp
  strelyaev.roman/S2/main.cpp
  strelyaev.roman/S2/queue.hpp
  strelyaev.roman/S2/stack.hpp
  strelyaev.roman/S2/token.cpp
  strelyaev.roman/S2/token.hpp
  strelyaev.roman/common/list/constIterator.hpp
  strelyaev.roman/common/list/iterator.hpp
  strelyaev.roman/common/list/list.hpp
  strelyaev.roman/common/list/node.hpp
Labels: fine, -2

#34 novokhatskiy.danil/S1
  novokhatskiy.danil/S1/const_forward_list_iterators.hpp
  novokhatskiy.danil/S1/forward_list.hpp
  novokhatskiy.danil/S1/forward_list_iterators.hpp
  novokhatskiy.danil/S1/main.cpp
  novokhatskiy.danil/S1/node.hpp
Labels: fine

#43 sivkov.filipp/S1
  sivkov.filipp/S1/inputOutput.cpp
  sivkov.filipp/S1/inputOutput.hpp
  sivkov.filipp/S1/main.cpp
  sivkov.filipp/common/constIterator.hpp
  sivkov.filipp/common/list.hpp
  sivkov.filipp/common/node.hpp
Labels: fine, trash, -1, 3

#83 piyavkin.anton/S4
  piyavkin.anton/S4/commands.cpp
  piyavkin.anton/S4/commands.hpp
  piyavkin.anton/S4/inputfile.cpp
  piyavkin.anton/S4/inputfile.hpp
  piyavkin.anton/S4/main.cpp
  piyavkin.anton/S4/tree.hpp
  piyavkin.anton/S4/treeiterator.hpp
  piyavkin.anton/S4/treenode.hpp
Labels: fine

#63 zaitsev.vladimir/S2
  zaitsev.vladimir/S1/lists_i_o.cpp
  zaitsev.vladimir/S1/lists_i_o.hpp
  zaitsev.vladimir/S2/deque.hpp
  zaitsev.vladimir/S2/main.cpp
  zaitsev.vladimir/S2/operators.cpp
  zaitsev.vladimir/S2/operators.hpp
  zaitsev.vladimir/S2/postfix_expression.cpp
  zaitsev.vladimir/S2/postfix_expression.hpp
  zaitsev.vladimir/S2/queue.hpp
  zaitsev.vladimir/S2/stack.hpp
  zaitsev.vladimir/S2/token.cpp
  zaitsev.vladimir/S2/token.hpp
  zaitsev.vladimir/common/forward_list.hpp
Labels: fine, -2

#49 grechishnikov.roman/S1
  grechishnikov.roman/S1/constIterator.hpp
  grechishnikov.roman/S1/iterator.hpp
  grechishnikov.roman/S1/list.hpp
  grechishnikov.roman/S1/listFunctions.cpp
  grechishnikov.roman/S1/listFunctions.hpp
  grechishnikov.roman/S1/main.cpp
  grechishnikov.roman/S1/node.hpp
Labels: fine, -1

#71 gladyshev.matvey/S2
  gladyshev.matvey/S1/inputlist.hpp
  gladyshev.matvey/S1/main.cpp
  gladyshev.matvey/S2/checkdata.cpp
  gladyshev.matvey/S2/checkdata.hpp
  gladyshev.matvey/S2/main.cpp
  gladyshev.matvey/S2/queue.hpp
  gladyshev.matvey/S2/solvedata.cpp
  gladyshev.matvey/S2/solvedata.hpp
  gladyshev.matvey/S2/stack.hpp
  gladyshev.matvey/S2/topostfix.cpp
  gladyshev.matvey/S2/topostfix.hpp
  gladyshev.matvey/common/constiterator.hpp
  gladyshev.matvey/common/iterator.hpp
  gladyshev.matvey/common/list.hpp
  gladyshev.matvey/common/node.hpp
Labels: fine

#105 piyavkin.anton/S5
  piyavkin.anton/S4/commands.hpp
  piyavkin.anton/S4/inputfile.hpp
  piyavkin.anton/S5/commands.cpp
  piyavkin.anton/S5/commands.hpp
  piyavkin.anton/S5/keysum.cpp
  piyavkin.anton/S5/keysum.hpp
  piyavkin.anton/S5/main.cpp
  piyavkin.anton/S5/specialiterator.hpp
  piyavkin.anton/common/queue.hpp
  piyavkin.anton/common/stack.hpp
  piyavkin.anton/common/tree.hpp
  piyavkin.anton/common/treeiterator.hpp
  piyavkin.anton/common/treenode.hpp
Labels: fine

#57 baranov.pavel/S1
  baranov.pavel/S1/constIterator.hpp
  baranov.pavel/S1/inputList.cpp
  baranov.pavel/S1/inputList.hpp
  baranov.pavel/S1/iterator.hpp
  baranov.pavel/S1/list.hpp
  baranov.pavel/S1/listFunctions.cpp
  baranov.pavel/S1/listFunctions.hpp
  baranov.pavel/S1/main.cpp
  baranov.pavel/S1/node.hpp
  baranov.pavel/S1/outputFunctions.cpp
  baranov.pavel/S1/outputFunctions.hpp
Labels: fine

#80 zhalilov.rail/S4
  zhalilov.rail/S4/commands.cpp
  zhalilov.rail/S4/commands.hpp
  zhalilov.rail/S4/const_treeIterator.hpp
  zhalilov.rail/S4/getMaps.cpp
  zhalilov.rail/S4/getMaps.hpp
  zhalilov.rail/S4/main.cpp
  zhalilov.rail/S4/mapMaster.cpp
  zhalilov.rail/S4/mapMaster.hpp
  zhalilov.rail/S4/treeIterator.hpp
  zhalilov.rail/S4/treeNode.hpp
  zhalilov.rail/S4/twoThreeTree.hpp
Labels: fine

#65 Namestnikov.kirill/S2
  namestnikov.kirill/S2/calculate_postfix_expression.cpp
  namestnikov.kirill/S2/calculate_postfix_expression.hpp
  namestnikov.kirill/S2/convert_to_postfix.cpp
  namestnikov.kirill/S2/convert_to_postfix.hpp
  namestnikov.kirill/S2/data_types.cpp
  namestnikov.kirill/S2/data_types.hpp
  namestnikov.kirill/S2/input_expressions.cpp
  namestnikov.kirill/S2/input_expressions.hpp
  namestnikov.kirill/S2/main.cpp
  namestnikov.kirill/S2/queue.hpp
  namestnikov.kirill/S2/stack.hpp
  namestnikov.kirill/common/const_iterators.hpp
  namestnikov.kirill/common/forward_list.hpp
  namestnikov.kirill/common/iterators.hpp
  namestnikov.kirill/common/node.hpp
Labels: fine

#97 Nikitov.dmitriy/S4
  nikitov.dmitriy/S4/commands.cpp
  nikitov.dmitriy/S4/commands.hpp
  nikitov.dmitriy/S4/const_tree_iterator.hpp
  nikitov.dmitriy/S4/main.cpp
  nikitov.dmitriy/S4/read_dictionaries.cpp
  nikitov.dmitriy/S4/read_dictionaries.hpp
  nikitov.dmitriy/S4/tree.hpp
  nikitov.dmitriy/S4/tree_iterator.hpp
  nikitov.dmitriy/S4/tree_node.hpp
  nikitov.dmitriy/common/list.hpp
Labels: fine

#90 zakozhurnikova.kristina/S4
  zakozhurnikova.kristina/S4/commands.cpp
  zakozhurnikova.kristina/S4/commands.hpp
  zakozhurnikova.kristina/S4/implementedCommands.cpp
  zakozhurnikova.kristina/S4/implementedCommands.hpp
  zakozhurnikova.kristina/S4/inputMaps.cpp
  zakozhurnikova.kristina/S4/inputMaps.hpp
  zakozhurnikova.kristina/S4/main.cpp
  zakozhurnikova.kristina/common/binarySearchTree.hpp
  zakozhurnikova.kristina/common/constIteratorTree.hpp
  zakozhurnikova.kristina/common/list.hpp
  zakozhurnikova.kristina/common/scopeGuard.cpp
  zakozhurnikova.kristina/common/scopeGuard.hpp
  zakozhurnikova.kristina/common/treeNode.hpp
Labels: fine

#58 ishmuratov.eric/S2
  ishmuratov.eric/S2/checks.cpp
  ishmuratov.eric/S2/checks.hpp
  ishmuratov.eric/S2/infix_operations.cpp
  ishmuratov.eric/S2/infix_operations.hpp
  ishmuratov.eric/S2/main.cpp
  ishmuratov.eric/S2/postfix_operations.cpp
  ishmuratov.eric/S2/postfix_operations.hpp
  ishmuratov.eric/S2/queue.hpp
  ishmuratov.eric/S2/stack.hpp
Labels: fine, -1

#54 skuratov.danil/S1
  skuratov.danil/S1/constIterators.hpp
  skuratov.danil/S1/inputOutput.cpp
  skuratov.danil/S1/inputOutput.hpp
  skuratov.danil/S1/list.hpp
  skuratov.danil/S1/main.cpp
  skuratov.danil/S1/node.hpp
Labels: fine

#85 sivkov.filipp/S2
  sivkov.filipp/S2/expressionEvaluation.cpp
  sivkov.filipp/S2/expressionEvaluation.hpp
  sivkov.filipp/S2/infixToPostfix.cpp
  sivkov.filipp/S2/infixToPostfix.hpp
  sivkov.filipp/S2/input.cpp
  sivkov.filipp/S2/input.hpp
  sivkov.filipp/S2/main.cpp
  sivkov.filipp/S2/utilities.cpp
  sivkov.filipp/S2/utilities.hpp
  sivkov.filipp/common/queue.hpp
  sivkov.filipp/common/stack.hpp
Labels: fine

#86 erohin.vladimir/S4
  erohin.vladimir/S4/dictionary_command.cpp
  erohin.vladimir/S4/dictionary_command.hpp
  erohin.vladimir/S4/input_output_collection.cpp
  erohin.vladimir/S4/input_output_collection.hpp
  erohin.vladimir/S4/main.cpp
  erohin.vladimir/S4/red_black_tree.hpp
  erohin.vladimir/S4/tree_const_iterator.hpp
  erohin.vladimir/S4/tree_iterator.hpp
  erohin.vladimir/S4/tree_node.hpp
Labels: fine

#106 zakozhurnikova.kristina/S5
  zakozhurnikova.kristina/S5/commands.cpp
  zakozhurnikova.kristina/S5/commands.hpp
  zakozhurnikova.kristina/S5/getSum.cpp
  zakozhurnikova.kristina/S5/getSum.hpp
  zakozhurnikova.kristina/S5/inputMap.cpp
  zakozhurnikova.kristina/S5/inputMap.hpp
  zakozhurnikova.kristina/S5/main.cpp
  zakozhurnikova.kristina/common/binarySearchTree.hpp
  zakozhurnikova.kristina/common/constIteratorTree.hpp
  zakozhurnikova.kristina/common/queue.hpp
  zakozhurnikova.kristina/common/stack.hpp
Labels: fine

#113 zhalilov.rail/S5
  zhalilov.rail/S2/calculateExpr.hpp
  zhalilov.rail/S2/getInfix.hpp
  zhalilov.rail/S2/infixToPostfix.cpp
  zhalilov.rail/S2/infixToPostfix.hpp
  zhalilov.rail/S2/main.cpp
  zhalilov.rail/S4/commands.hpp
  zhalilov.rail/S4/getMaps.cpp
  zhalilov.rail/S4/getMaps.hpp
  zhalilov.rail/S4/main.cpp
  zhalilov.rail/S4/mapMaster.hpp
  zhalilov.rail/S5/main.cpp
  zhalilov.rail/S5/summator.cpp
  zhalilov.rail/S5/summator.hpp
  zhalilov.rail/common/queue.hpp
  zhalilov.rail/common/tree/const_treeIterator.hpp
  zhalilov.rail/common/tree/treeIterator.hpp
  zhalilov.rail/common/tree/treeNode.hpp
  zhalilov.rail/common/tree/twoThreeTree.hpp
Labels: fine

#52 lebedev.anton/S1
  lebedev.anton/S1/io_datastruct.cpp
  lebedev.anton/S1/io_datastruct.hpp
  lebedev.anton/S1/main.cpp
  lebedev.anton/common/list/const_list_iterator.hpp
  lebedev.anton/common/list/list.hpp
  lebedev.anton/common/list/list_iterator.hpp
  lebedev.anton/common/list/node.hpp
Labels: fine

#114 erohin.vladimir/S5
  erohin.vladimir/S5/breadth_iterator.hpp
  erohin.vladimir/S5/complement_functor.cpp
  erohin.vladimir/S5/complement_functor.hpp
  erohin.vladimir/S5/const_breadth_iterator.hpp
  erohin.vladimir/S5/const_lnr_iterator.hpp
  erohin.vladimir/S5/const_rnl_iterator.hpp
  erohin.vladimir/S5/lnr_iterator.hpp
  erohin.vladimir/S5/main.cpp
  erohin.vladimir/S5/rnl_iterator.hpp
  erohin.vladimir/common/dyn_array_const_iterator.hpp
  erohin.vladimir/common/dyn_array_iterator.hpp
  erohin.vladimir/common/dynamic_array.hpp
  erohin.vladimir/common/queue.hpp
  erohin.vladimir/common/red_black_tree.hpp
  erohin.vladimir/common/stack.hpp
  erohin.vladimir/common/tree_const_iterator.hpp
  erohin.vladimir/common/tree_iterator.hpp
  erohin.vladimir/common/tree_node.hpp
Labels: fine

#81 zaitsev.vladimir/S4
  zaitsev.vladimir/S4/commands_processing.cpp
  zaitsev.vladimir/S4/commands_processing.hpp
  zaitsev.vladimir/S4/main.cpp
  zaitsev.vladimir/S4/map.hpp
Labels: fine

#111 skuratov.danil/S2
  skuratov.danil/S1/inputOutput.cpp
  skuratov.danil/S1/inputOutput.hpp
  skuratov.danil/S2/evaluatePostfix.cpp
  skuratov.danil/S2/evaluatePostfix.hpp
  skuratov.danil/S2/infixToPostfix.cpp
  skuratov.danil/S2/infixToPostfix.hpp
  skuratov.danil/S2/main.cpp
  skuratov.danil/S2/queue.hpp
  skuratov.danil/S2/stack.hpp
  skuratov.danil/common/constIterators.hpp
  skuratov.danil/common/list.hpp
  skuratov.danil/common/node.hpp
Labels: fine

#125 zaitsev.vladimir/S5
  zaitsev.vladimir/S2/main.cpp
  zaitsev.vladimir/S2/postfix_expression.hpp
  zaitsev.vladimir/S2/token.cpp
  zaitsev.vladimir/S4/commands_processing.cpp
  zaitsev.vladimir/S4/commands_processing.hpp
  zaitsev.vladimir/S4/main.cpp
  zaitsev.vladimir/S5/main.cpp
  zaitsev.vladimir/S5/summator.cpp
  zaitsev.vladimir/S5/summator.hpp
  zaitsev.vladimir/common/deque.hpp
  zaitsev.vladimir/common/map.hpp
  zaitsev.vladimir/common/operators.cpp
  zaitsev.vladimir/common/operators.hpp
  zaitsev.vladimir/common/queue.hpp
  zaitsev.vladimir/common/stack.hpp
Labels: fine

#89 Namestnikov.kirill/S4
  namestnikov.kirill/S4/commands.cpp
  namestnikov.kirill/S4/commands.hpp
  namestnikov.kirill/S4/input_dicts.cpp
  namestnikov.kirill/S4/input_dicts.hpp
  namestnikov.kirill/S4/main.cpp
  namestnikov.kirill/common/const_tree_iterator.hpp
  namestnikov.kirill/common/tree.hpp
  namestnikov.kirill/common/tree_iterator.hpp
  namestnikov.kirill/common/tree_node.hpp
Labels: fine

#124 erohin.vladimir/S6
  erohin.vladimir/S5/breadth_iterator.hpp
  erohin.vladimir/S5/const_breadth_iterator.hpp
  erohin.vladimir/S5/const_lnr_iterator.hpp
  erohin.vladimir/S5/const_rnl_iterator.hpp
  erohin.vladimir/S5/lnr_iterator.hpp
  erohin.vladimir/S5/rnl_iterator.hpp
  erohin.vladimir/S6/main.cpp
  erohin.vladimir/S6/sequence_operations.hpp
  erohin.vladimir/S6/sort_command.hpp
  erohin.vladimir/S6/sort_functions.hpp
  erohin.vladimir/common/list.hpp
  erohin.vladimir/common/list_const_iterator.hpp
  erohin.vladimir/common/list_iterator.hpp
  erohin.vladimir/common/node.hpp
  erohin.vladimir/common/red_black_tree.hpp
  erohin.vladimir/common/tree_const_iterator.hpp
  erohin.vladimir/common/tree_iterator.hpp
  erohin.vladimir/common/tree_node.hpp
Labels: fine

#92 gladyshev.matvey/S4
  gladyshev.matvey/S4/avltree.hpp
  gladyshev.matvey/S4/commands.cpp
  gladyshev.matvey/S4/commands.hpp
  gladyshev.matvey/S4/inputdata.cpp
  gladyshev.matvey/S4/inputdata.hpp
  gladyshev.matvey/S4/main.cpp
  gladyshev.matvey/S4/processcommands.cpp
  gladyshev.matvey/S4/processcommands.hpp
  gladyshev.matvey/S4/treeiterator.hpp
  gladyshev.matvey/S4/treenode.hpp
Labels: fine

#112 piyavkin.anton/S6
  piyavkin.anton/S6/createcontainer.cpp
  piyavkin.anton/S6/createcontainer.hpp
  piyavkin.anton/S6/main.cpp
  piyavkin.anton/S6/merge.hpp
  piyavkin.anton/S6/printsortcontainers.hpp
  piyavkin.anton/S6/streamguard.cpp
  piyavkin.anton/S6/streamguard.hpp
  piyavkin.anton/S6/timsort.hpp
  piyavkin.anton/common/list.hpp
  piyavkin.anton/common/listiterator.hpp
Labels: fine

#116 Nikitov.dmitriy/S6
  nikitov.dmitriy/S6/iterators_functions.hpp
  nikitov.dmitriy/S6/main.cpp
  nikitov.dmitriy/S6/sort_sequence.hpp
  nikitov.dmitriy/S6/sortings.hpp
  nikitov.dmitriy/common/list.hpp
  nikitov.dmitriy/common/tree_node.hpp
Labels: fine

#128 zaitsev.vladimir/S6
  zaitsev.vladimir/S1/lists_i_o.cpp
  zaitsev.vladimir/S6/executor.hpp
  zaitsev.vladimir/S6/generators.hpp
  zaitsev.vladimir/S6/main.cpp
  zaitsev.vladimir/S6/sorting_algorithms.hpp
  zaitsev.vladimir/common/forward_list.hpp
Labels: fine

#126 zhalilov.rail/S6
  zhalilov.rail/S6/main.cpp
  zhalilov.rail/S6/sortAlgorithms.hpp
  zhalilov.rail/S6/testSorts.hpp
  zhalilov.rail/common/list/const_iterator.hpp
  zhalilov.rail/common/list/iterator.hpp
  zhalilov.rail/common/list/list.hpp
Labels: fine

#110 zakozhurnikova.kristina/S6
  zakozhurnikova.kristina/S6/generate.cpp
  zakozhurnikova.kristina/S6/generate.hpp
  zakozhurnikova.kristina/S6/main.cpp
  zakozhurnikova.kristina/S6/print.hpp
  zakozhurnikova.kristina/S6/sorting.hpp
  zakozhurnikova.kristina/S6/sortingSheets.hpp
  zakozhurnikova.kristina/common/list.hpp
Labels: fine

#115 Namestnikov.kirill/S5
  namestnikov.kirill/S5/commands.cpp
  namestnikov.kirill/S5/commands.hpp
  namestnikov.kirill/S5/input_dict.cpp
  namestnikov.kirill/S5/input_dict.hpp
  namestnikov.kirill/S5/main.cpp
  namestnikov.kirill/S5/sum_func.cpp
  namestnikov.kirill/S5/sum_func.hpp
  namestnikov.kirill/common/const_tree_iterator.hpp
  namestnikov.kirill/common/queue.hpp
  namestnikov.kirill/common/stack.hpp
  namestnikov.kirill/common/tree.hpp
  namestnikov.kirill/common/tree_iterator.hpp
Labels: fine
