Repository Volgarenok/spbspu-labs-2024-aads-a, pull requests merged in 2024-04, with the labels that each got.

#60 vyzhanov.daniil/S0
  vyzhanov.daniil/S0/main.cpp
Labels: fine

#29 zhalilov.rail/S1
  zhalilov.rail/S1/getSeqFromStream.cpp
  zhalilov.rail/S1/getSeqFromStream.hpp
  zhalilov.rail/S1/main.cpp
  zhalilov.rail/S1/outputList.hpp
  zhalilov.rail/S1/outputSeqs.cpp
  zhalilov.rail/S1/outputSeqs.hpp
  zhalilov.rail/common/list/const_iterator.hpp
  zhalilov.rail/common/list/iterator.hpp
  zhalilov.rail/common/list/list.hpp
  zhalilov.rail/common/list/node.hpp
Labels: fine

#30 piyavkin.anton/S1
  piyavkin.anton/S1/inputlist.cpp
  piyavkin.anton/S1/inputlist.hpp
  piyavkin.anton/S1/main.cpp
  piyavkin.anton/S1/output.cpp
  piyavkin.anton/S1/output.hpp
  piyavkin.anton/common/list.hpp
  piyavkin.anton/common/listiterator.hpp
  piyavkin.anton/common/node.hpp
Labels: fine, 5, -2

#78 dobsov.sergey/s0
  dobsov.sergey/S0/main.cpp
Labels: fine

#38 zaitsev.vladimir/S1
  zaitsev.vladimir/S1/forward_list.hpp
  zaitsev.vladimir/S1/lists_i_o.cpp
  zaitsev.vladimir/S1/lists_i_o.hpp
  zaitsev.vladimir/S1/main.cpp
Labels: fine, -2

#33 Nikitov.dmitriy/S1
  nikitov.dmitriy/S1/input_list.cpp
  nikitov.dmitriy/S1/input_list.hpp
  nikitov.dmitriy/S1/main.cpp
  nikitov.dmitriy/S1/output_list.cpp
  nikitov.dmitriy/S1/output_list.hpp
  nikitov.dmitriy/common/const_list_iterator.hpp
  nikitov.dmitriy/common/list.hpp
  nikitov.dmitriy/common/list_iterator.hpp
  nikitov.dmitriy/common/node.hpp
Labels: fine

#69 zhalilov.rail/S2
  zhalilov.rail/S2/binaryOperator.cpp
  zhalilov.rail/S2/binaryOperator.hpp
  zhalilov.rail/S2/bracket.cpp
  zhalilov.rail/S2/bracket.hpp
  zhalilov.rail/S2/calculateExpr.cpp
  zhalilov.rail/S2/calculateExpr.hpp
  zhalilov.rail/S2/expressionTokens.cpp
  zhalilov.rail/S2/expressionTokens.hpp
  zhalilov.rail/S2/getInfix.cpp
  zhalilov.rail/S2/getInfix.hpp
  zhalilov.rail/S2/infixToPostfix.cpp
  zhalilov.rail/S2/infixToPostfix.hpp
  zhalilov.rail/S2/main.cpp
  zhalilov.rail/S2/operand.cpp
  zhalilov.rail/S2/operand.hpp
  zhalilov.rail/S2/primaryType.hpp
  zhalilov.rail/S2/queue.hpp
  zhalilov.rail/S2/stack.hpp
Labels: fine, -2

#36 ishmuratov.eric/S1
  ishmuratov.eric/S1/input.cpp
  ishmuratov.eric/S1/input.hpp
  ishmuratov.eric/S1/main.cpp
  ishmuratov.eric/common/bdlist.hpp
  ishmuratov.eric/common/iterator.hpp
  ishmuratov.eric/common/node.hpp
Labels: fine, -1, 5

#47 strelyaev.roman/S1
  strelyaev.roman/S1/constIterator.hpp
  strelyaev.roman/S1/inputList.cpp
  strelyaev.roman/S1/inputList.hpp
  strelyaev.roman/S1/iterator.hpp
  strelyaev.roman/S1/list.hpp
  strelyaev.roman/S1/main.cpp
  strelyaev.roman/S1/node.hpp
Labels: fine, -2, dead-weight

#44 arakelyan.daniil/s1
  arakelyan.daniil/S1/inputData.cpp
  arakelyan.daniil/S1/inputData.hpp
  arakelyan.daniil/S1/main.cpp
  arakelyan.daniil/S1/outputData.cpp
  arakelyan.daniil/S1/outputData.hpp
  arakelyan.daniil/common/list/binList.hpp
  arakelyan.daniil/common/list/constIterator.hpp
  arakelyan.daniil/common/list/iterator.hpp
  arakelyan.daniil/common/list/node.hpp
Labels: fine, -1, dead-weight

#48 zakozhurnikova.kristina/S1
  zakozhurnikova.kristina/S1/constIterator.hpp
  zakozhurnikova.kristina/S1/inputOperations.cpp
  zakozhurnikova.kristina/S1/inputOperations.hpp
  zakozhurnikova.kristina/S1/iterator.hpp
  zakozhurnikova.kristina/S1/list.hpp
  zakozhurnikova.kristina/S1/main.cpp
  zakozhurnikova.kristina/S1/node.hpp
  zakozhurnikova.kristina/S1/print.cpp
  zakozhurnikova.kristina/S1/print.hpp
Labels: fine, -1

#55 isaychev.vladislav/S1
  isaychev.vladislav/S1/cIterator.hpp
  isaychev.vladislav/S1/inputList.cpp
  isaychev.vladislav/S1/inputList.hpp
  isaychev.vladislav/S1/iterator.hpp
  isaychev.vladislav/S1/list.hpp
  isaychev.vladislav/S1/listManipulations.cpp
  isaychev.vladislav/S1/listManipulations.hpp
  isaychev.vladislav/S1/main.cpp
  isaychev.vladislav/S1/node.hpp
  isaychev.vladislav/S1/outputResults.cpp
  isaychev.vladislav/S1/outputResults.hpp
Labels: fine, -1

#45 erohin.vladimir/S1
  erohin.vladimir/S1/input_named_list.cpp
  erohin.vladimir/S1/input_named_list.hpp
  erohin.vladimir/S1/list.hpp
  erohin.vladimir/S1/list_const_iterator.hpp
  erohin.vladimir/S1/list_iterator.hpp
  erohin.vladimir/S1/main.cpp
  erohin.vladimir/S1/node.hpp
  erohin.vladimir/S1/output_named_list.cpp
  erohin.vladimir/S1/output_named_list.hpp
Labels: fine, 5, -2

#59 piyavkin.anton/S2
  piyavkin.anton/S2/calculate.cpp
  piyavkin.anton/S2/calculate.hpp
  piyavkin.anton/S2/convertpostfix.cpp
  piyavkin.anton/S2/convertpostfix.hpp
  piyavkin.anton/S2/input.cpp
  piyavkin.anton/S2/input.hpp
  piyavkin.anton/S2/main.cpp
  piyavkin.anton/S2/queue.hpp
  piyavkin.anton/S2/stack.hpp
  piyavkin.anton/S2/types.cpp
  piyavkin.anton/S2/types.hpp
Labels: fine, -2

#32 namestnikov.kirill/S1
  namestnikov.kirill/S1/const_iterators.hpp
  namestnikov.kirill/S1/forward_list.hpp
  namestnikov.kirill/S1/input_output_lists.cpp
  namestnikov.kirill/S1/input_output_lists.hpp
  namestnikov.kirill/S1/iterators.hpp
  namestnikov.kirill/S1/main.cpp
  namestnikov.kirill/S1/node.hpp
Labels: fine, -1

#62 Nikitov.dmitriy/S2
  nikitov.dmitriy/S2/convert_expression.cpp
  nikitov.dmitriy/S2/convert_expression.hpp
  nikitov.dmitriy/S2/expression_types.cpp
  nikitov.dmitriy/S2/expression_types.hpp
  nikitov.dmitriy/S2/infix_type.cpp
  nikitov.dmitriy/S2/infix_type.hpp
  nikitov.dmitriy/S2/input_expressions.cpp
  nikitov.dmitriy/S2/input_expressions.hpp
  nikitov.dmitriy/S2/main.cpp
  nikitov.dmitriy/S2/postfix_expression.cpp
  nikitov.dmitriy/S2/postfix_expression.hpp
  nikitov.dmitriy/S2/postfix_type.cpp
  nikitov.dmitriy/S2/postfix_type.hpp
  nikitov.dmitriy/S2/queue.hpp
  nikitov.dmitriy/S2/stack.hpp
  nikitov.dmitriy/S2/stack_type.cpp
  nikitov.dmitriy/S2/stack_type.hpp
  nikitov.dmitriy/common/list.hpp
Labels: fine, -2

#82 vojuck.victoria/S0
  vojuck.victoria/S0/main.cpp
Labels: fine

#66 erohin.vladimir/S2
  erohin.vladimir/S2/bracket.hpp
  erohin.vladimir/S2/dyn_array_const_iterator.hpp
  erohin.vladimir/S2/dyn_array_iterator.hpp
  erohin.vladimir/S2/dynamic_array.hpp
  erohin.vladimir/S2/infix_expression.cpp
  erohin.vladimir/S2/infix_expression.hpp
  erohin.vladimir/S2/main.cpp
  erohin.vladimir/S2/operand.cpp
  erohin.vladimir/S2/operand.hpp
  erohin.vladimir/S2/operator.cpp
  erohin.vladimir/S2/operator.hpp
  erohin.vladimir/S2/postfix_expression.cpp
  erohin.vladimir/S2/postfix_expression.hpp
  erohin.vladimir/S2/queue.hpp
  erohin.vladimir/S2/stack.hpp
  erohin.vladimir/S2/token.hpp
Labels: fine, -2

#67 zakozhurnikova.kristina/S2
  zakozhurnikova.kristina/S1/inputOperations.hpp
  zakozhurnikova.kristina/S1/main.cpp
  zakozhurnikova.kristina/S1/print.hpp
  zakozhurnikova.kristina/S2/evaluatePostfix.cpp
  zakozhurnikova.kristina/S2/evaluatePostfix.hpp
  zakozhurnikova.kristina/S2/getPostfixFromInfix.cpp
  zakozhurnikova.kristina/S2/getPostfixFromInfix.hpp
  zakozhurnikova.kristina/S2/main.cpp
  zakozhurnikova.kristina/S2/outputResult.cpp
  zakozhurnikova.kristina/S2/outputResult.hpp
  zakozhurnikova.kristina/S2/queue.hpp
  zakozhurnikova.kristina/S2/readWord.cpp
  zakozhurnikova.kristina/S2/readWord.hpp
  zakozhurnikova.kristina/S2/stack.hpp
  zakozhurnikova.kristina/common/constIterator.hpp
  zakozhurnikova.kristina/common/iterator.hpp
  zakozhurnikova.kristina/common/list.hpp
  zakozhurnikova.kristina/common/node.hpp
Labels: fine, -1

#31 rebdev.pavel/S1
  rebdev.pavel/S1/BidirectionalIterator.hpp
  rebdev.pavel/S1/biListNode.hpp
  rebdev.pavel/S1/constBidirectionalIterator.hpp
  rebdev.pavel/S1/list.hpp
  rebdev.pavel/S1/listFunction.cpp
  rebdev.pavel/S1/listFunction.hpp
  rebdev.pavel/S1/main.cpp
Labels: fine, -1
