Repository Volgarenok/spbspu-labs-2024-aads-a, pull requests merged in 2024-06, with the labels that each got.

#139 erohin.vladimir/F0
  erohin.vladimir/F0/collection_commands.cpp
  erohin.vladimir/F0/collection_commands.hpp
  erohin.vladimir/F0/delimiter.hpp
  erohin.vladimir/F0/dictionary.cpp
  erohin.vladimir/F0/dictionary.hpp
  erohin.vladimir/F0/dictionary_record.cpp
  erohin.vladimir/F0/dictionary_record.hpp
  erohin.vladimir/F0/input_output_collection.cpp
  erohin.vladimir/F0/input_output_collection.hpp
  erohin.vladimir/F0/main.cpp
  erohin.vladimir/F0/number_format.cpp
  erohin.vladimir/F0/number_format.hpp
  erohin.vladimir/F0/scope_guard.cpp
  erohin.vladimir/F0/scope_guard.hpp
  erohin.vladimir/F0/secondary_commands.cpp
  erohin.vladimir/F0/secondary_commands.hpp
  erohin.vladimir/F0/string_format.cpp
  erohin.vladimir/F0/string_format.hpp
  erohin.vladimir/S5/const_rnl_iterator.hpp
  erohin.vladimir/common/red_black_tree.hpp
  erohin.vladimir/common/tree_node.hpp
Labels: fine, 5

#138 Nikitov.dmitriy/F0
  nikitov.dmitriy/F0/commands.cpp
  nikitov.dmitriy/F0/commands.hpp
  nikitov.dmitriy/F0/delimiter.cpp
  nikitov.dmitriy/F0/delimiter.hpp
  nikitov.dmitriy/F0/dictionary.cpp
  nikitov.dmitriy/F0/dictionary.hpp
  nikitov.dmitriy/F0/main.cpp
  nikitov.dmitriy/F0/word.cpp
  nikitov.dmitriy/F0/word.hpp
  nikitov.dmitriy/common/tree.hpp
Labels: fine, 5

#134 piyavkin.anton/F0
  piyavkin.anton/F0/comlinearg.cpp
  piyavkin.anton/F0/comlinearg.hpp
  piyavkin.anton/F0/commands.cpp
  piyavkin.anton/F0/commands.hpp
  piyavkin.anton/F0/main.cpp
  piyavkin.anton/common/tree.hpp
Labels: fine, 5

#135 zakozhurnikova.kristina/F0
  zakozhurnikova.kristina/F0/commands.cpp
  zakozhurnikova.kristina/F0/commands.hpp
  zakozhurnikova.kristina/F0/inputDictionary.cpp
  zakozhurnikova.kristina/F0/inputDictionary.hpp
  zakozhurnikova.kristina/F0/main.cpp
Labels: fine, 5

#137 zhalilov.rail/F0
  zhalilov.rail/F0/commands.cpp
  zhalilov.rail/F0/commands.hpp
  zhalilov.rail/F0/main.cpp
  zhalilov.rail/S2/getInfix.cpp
  zhalilov.rail/S2/getInfix.hpp
  zhalilov.rail/S2/main.cpp
  zhalilov.rail/common/binaryOperator.cpp
  zhalilov.rail/common/bracket.cpp
  zhalilov.rail/common/calc/binaryOperator.hpp
  zhalilov.rail/common/calc/bracket.hpp
  zhalilov.rail/common/calc/calculateExpr.hpp
  zhalilov.rail/common/calc/expressionTokens.hpp
  zhalilov.rail/common/calc/getInfix.hpp
  zhalilov.rail/common/calc/infixToPostfix.hpp
  zhalilov.rail/common/calc/operand.hpp
  zhalilov.rail/common/calc/primaryType.hpp
  zhalilov.rail/common/calc/varExpression.hpp
  zhalilov.rail/common/calculateExpr.cpp
  zhalilov.rail/common/expressionTokens.cpp
  zhalilov.rail/common/getInfix.cpp
  zhalilov.rail/common/infixToPostfix.cpp
  zhalilov.rail/common/list/list.hpp
  zhalilov.rail/common/listQueueCasting.hpp
  zhalilov.rail/common/operand.cpp
  zhalilov.rail/common/stack.hpp
  zhalilov.rail/common/tree/twoThreeTree.hpp
  zhalilov.rail/common/varExpression.cpp
Labels: fine, 5

#127 gladyshev.matvey/S5
  gladyshev.matvey/S2/solvedata.hpp
  gladyshev.matvey/S2/topostfix.hpp
  gladyshev.matvey/S4/commands.hpp
  gladyshev.matvey/S4/inputdata.hpp
  gladyshev.matvey/S5/main.cpp
  gladyshev.matvey/S5/sumfunc.cpp
  gladyshev.matvey/S5/sumfunc.hpp
  gladyshev.matvey/common/avltree.hpp
  gladyshev.matvey/common/queue.hpp
  gladyshev.matvey/common/treeiterator.hpp
  gladyshev.matvey/common/treenode.hpp
Labels: fine

#140 zaitsev.vladimir/F0
  zaitsev.vladimir/F0/delimiter.cpp
  zaitsev.vladimir/F0/delimiter.hpp
  zaitsev.vladimir/F0/graphs_base.cpp
  zaitsev.vladimir/F0/graphs_base.hpp
  zaitsev.vladimir/F0/i_o_processing.cpp
  zaitsev.vladimir/F0/i_o_processing.hpp
  zaitsev.vladimir/F0/main.cpp
  zaitsev.vladimir/F0/path_search.cpp
  zaitsev.vladimir/F0/path_search.hpp
  zaitsev.vladimir/F0/stream_guard.cpp
  zaitsev.vladimir/F0/stream_guard.hpp
  zaitsev.vladimir/common/map.hpp
Labels: fine

#93 sivkov.filipp/S4
  sivkov.filipp/S4/cmd.cpp
  sivkov.filipp/S4/cmd.hpp
  sivkov.filipp/S4/input.cpp
  sivkov.filipp/S4/input.hpp
  sivkov.filipp/S4/main.cpp
  sivkov.filipp/common/AVLTree.hpp
  sivkov.filipp/common/cIterator.hpp
  sivkov.filipp/common/treeNode.hpp
Labels: fine

#146 strelyaev.roman/S6
  strelyaev.roman/S6/chooseSort.hpp
  strelyaev.roman/S6/generate.cpp
  strelyaev.roman/S6/generate.hpp
  strelyaev.roman/S6/main.cpp
  strelyaev.roman/S6/print.hpp
  strelyaev.roman/S6/sorts.hpp
  strelyaev.roman/common/list/iterator.hpp
  strelyaev.roman/common/list/list.hpp
Labels: fine

#142 gladyshev.matvey/S6
  gladyshev.matvey/S6/main.cpp
  gladyshev.matvey/S6/sortprocessing.hpp
  gladyshev.matvey/S6/sorts.hpp
Labels: fine

#117 marishin.leonid/S5
  marishin.leonid/S2/checksPostfix.cpp
  marishin.leonid/S2/checksPostfix.hpp
  marishin.leonid/S2/getPostfixForm.cpp
  marishin.leonid/S2/getPostfixForm.hpp
  marishin.leonid/S2/main.cpp
  marishin.leonid/S2/output.hpp
  marishin.leonid/S5/command.cpp
  marishin.leonid/S5/command.hpp
  marishin.leonid/S5/concatString.cpp
  marishin.leonid/S5/concatString.hpp
  marishin.leonid/S5/inputMaps.cpp
  marishin.leonid/S5/inputMaps.hpp
  marishin.leonid/S5/main.cpp
  marishin.leonid/S5/sumFunc.cpp
  marishin.leonid/S5/sumFunc.hpp
  marishin.leonid/S5/sumNum.cpp
  marishin.leonid/S5/sumNum.hpp
  marishin.leonid/common/binarySearchTree.hpp
  marishin.leonid/common/constTreeIterator.hpp
  marishin.leonid/common/queue.hpp
  marishin.leonid/common/stack.hpp
  marishin.leonid/common/treeIterator.hpp
Labels: fine

#147 strelyaev.roman/F0
  strelyaev.roman/F0/cmds.cpp
  strelyaev.roman/F0/cmds.hpp
  strelyaev.roman/F0/main.cpp
  strelyaev.roman/common/list/list.hpp
  strelyaev.roman/common/tree/binarySearchTree.hpp
Labels: fine, 4

#143 gladyshev.matvey/F0
  gladyshev.matvey/F0/commands.cpp
  gladyshev.matvey/F0/commands.hpp
  gladyshev.matvey/F0/inputdata.cpp
  gladyshev.matvey/F0/inputdata.hpp
  gladyshev.matvey/F0/main.cpp
Labels: fine, 5

#120 ishmuratov.eric/S5
  ishmuratov.eric/S5/commands.cpp
  ishmuratov.eric/S5/commands.hpp
  ishmuratov.eric/S5/input_data.cpp
  ishmuratov.eric/S5/input_data.hpp
  ishmuratov.eric/S5/key_summ.cpp
  ishmuratov.eric/S5/key_summ.hpp
  ishmuratov.eric/S5/main.cpp
  ishmuratov.eric/common/queue.hpp
  ishmuratov.eric/common/stack.hpp
  ishmuratov.eric/common/tree.hpp
  ishmuratov.eric/common/tree_iterator.hpp
  ishmuratov.eric/common/tree_node.hpp
Labels: fine

#129 Namestnikov.kirill/S6
  namestnikov.kirill/S6/main.cpp
  namestnikov.kirill/S6/selection_sort.hpp
  namestnikov.kirill/S6/shell_sort.hpp
  namestnikov.kirill/S6/test_sortings.hpp
  namestnikov.kirill/common/forward_list.hpp
Labels: fine

#133 ishmuratov.eric/S6
  ishmuratov.eric/S6/generate.hpp
  ishmuratov.eric/S6/main.cpp
  ishmuratov.eric/S6/merge_sort.hpp
  ishmuratov.eric/S6/quick_sort.hpp
Labels: fine

#148 Namestnikov.kirill/F0
  namestnikov.kirill/F0/commands.cpp
  namestnikov.kirill/F0/commands.hpp
  namestnikov.kirill/F0/delimeters.cpp
  namestnikov.kirill/F0/delimeters.hpp
  namestnikov.kirill/F0/input_output_data.cpp
  namestnikov.kirill/F0/input_output_data.hpp
  namestnikov.kirill/F0/main.cpp
  namestnikov.kirill/F0/stream_guard.cpp
  namestnikov.kirill/F0/stream_guard.hpp
  namestnikov.kirill/common/bidirectional_iterator.hpp
  namestnikov.kirill/common/bidirectional_list.hpp
  namestnikov.kirill/common/bidirectional_node.hpp
  namestnikov.kirill/common/const_bidirectional_iterator.hpp
  namestnikov.kirill/common/const_hash_table_iterators.hpp
  namestnikov.kirill/common/hash_table.hpp
  namestnikov.kirill/common/hash_table_iterators.hpp
  namestnikov.kirill/common/hash_table_node.hpp
Labels: fine

#123 sivkov.filipp/S6
  sivkov.filipp/S6/main.cpp
  sivkov.filipp/S6/outputInput.hpp
  sivkov.filipp/S6/sorts.hpp
Labels: fine

#131 sivkov.filipp/F0
  sivkov.filipp/F0/cmd.cpp
  sivkov.filipp/F0/cmd.hpp
  sivkov.filipp/F0/input.cpp
  sivkov.filipp/F0/input.hpp
  sivkov.filipp/F0/main.cpp
  sivkov.filipp/common/AVLTree.hpp
Labels: fine

#122 novokhatskiy.danil/S6
  novokhatskiy.danil/S6/main.cpp
  novokhatskiy.danil/S6/sortAndPrintSequence.hpp
  novokhatskiy.danil/S6/sortings.hpp
Labels: fine

#136 marishin.leonid/S6
  marishin.leonid/S6/main.cpp
  marishin.leonid/S6/print.hpp
  marishin.leonid/S6/sorting.hpp
  marishin.leonid/S6/sortingList.hpp
  marishin.leonid/common/iterator.hpp
  marishin.leonid/common/linkedList.hpp
Labels: fine

#132 novokhatskiy.danil/F0
  novokhatskiy.danil/F0/commands.cpp
  novokhatskiy.danil/F0/commands.hpp
  novokhatskiy.danil/F0/dictionary.cpp
  novokhatskiy.danil/F0/dictionary.hpp
  novokhatskiy.danil/F0/main.cpp
Labels: fine

#149 marishin.leonid/F0
  marishin.leonid/F0/main.cpp
Labels: fine, trash
